# This file is the main configuration file for the Django project.
# It contains settings for the database, installed applications, middleware, and other project-wide configurations.
# This file is crucial for the proper functioning of the Django application.
"""
Django settings for silent_library project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# Import necessary libraries
import os
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables from a .env file
load_dotenv()

# Define the base directory of the project
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# These are quick-start development settings. They are not suitable for a production environment.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: The secret key should be kept secret in a production environment.
# It is used for cryptographic signing.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: Debug mode should not be enabled in a production environment.
# It can expose sensitive information.
DEBUG = True

# A list of allowed host/domain names that this Django site can serve.
ALLOWED_HOSTS = []


# This section defines the applications that are installed in the Django project.
# Each app is a Python package that provides some functionality.
INSTALLED_APPS = [
    # Default Django apps
    "django.contrib.admin", # The admin site
    "django.contrib.auth", # Authentication framework
    "django.contrib.contenttypes", # Content type framework
    "django.contrib.sessions", # Session framework
    "django.contrib.messages", # Messaging framework
    "django.contrib.staticfiles", # Framework for managing static files
    # Custom apps
    "library", # The main application for the library project
]

# This section defines the middleware that is used in the Django project.
# Middleware is a framework of hooks into Django's request/response processing.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# This setting specifies the root URL configuration for the project.
# It is a string that points to the URL configuration module.
ROOT_URLCONF = "silent_library.urls"

# This section defines the template engines that are used in the Django project.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'silent_library', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# This setting specifies the WSGI application that is used by the Django development server.
WSGI_APPLICATION = "silent_library.wsgi.application"


# This section defines the database configuration for the project.
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv('DB_NAME'),
        "USER": os.getenv('DB_USER'),  # Replace with your MySQL username
        "PASSWORD": os.getenv('DB_PASSWORD'),  # Replace with your MySQL password
        "HOST": "localhost",  # Or your MySQL host
        "PORT": "3306",  # Or your MySQL port
    }
}


# This section defines the password validators that are used in the Django project.
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# This section defines the internationalization settings for the project.
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# This section defines the settings for static files (CSS, JavaScript, Images).
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"

# This setting defines the default primary key field type for models.
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# This setting specifies the custom user model that is used for authentication.
AUTH_USER_MODEL = "library.User"

# These settings define the URLs for login, login redirect, and logout redirect.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

############################ Email Configuration ############################
# This section configures the email settings for the project.
# It is used for sending emails, such as password reset emails.

# Email server configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#Gmail SMTP server settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Use TLS (recommended for Gmail)

# Authentication details
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # Your Gmail address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # The App Password you generated for Module 2

# Default sender address for emails
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# This section configures the logging for the project.
# It is used for logging errors and other information.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



