# This file contains the configuration properties for the Spring Boot application.

# --- Database Configuration ---
# The URL of the database. Here, we are using an in-memory H2 database named 'testdb'.
spring.datasource.url=jdbc:h2:mem:testdb
# The fully qualified name of the JDBC driver.
spring.datasource.driverClassName=org.h2.Driver
# The username for the database.
spring.datasource.username=sa
# The password for the database.
spring.datasource.password=password

# --- JPA Configuration ---
# The dialect to use for the H2 database. This tells Hibernate how to generate the appropriate SQL for the database.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
